{"name": "test_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_1():\n>       assert 1==2\nE       assert 1 == 2\n\ntestcase\\test_1.py:3: AssertionError"}, "start": 1573436617538, "stop": 1573436617539, "uuid": "56b9276c-526d-4aa2-bd9d-46ca48d42b54", "historyId": "cf53fb0cd5172238f8b56bb2dba8e9a4", "testCaseId": "2ce422121ac51e16b6e1739fc473b531", "fullName": "testcase.test_1#test_1", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1"}, {"name": "host", "value": "DESKTOP-HCRDV8N"}, {"name": "thread", "value": "10460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1"}]}